version: '3'

services:
    dbd_exam_rust_backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        environment:
          - PRODUCTION_VARIABLES=1
          - POSTGRES_HOST=pg_dbd_exam
          - POSTGRES_USER=softdbd_user
          - POSTGRES_PASSWORD=softdbd_pass
          - POSTGRES_DB=softdbd_db
          - POSTGRES_PORT=31295
          - MONGO_INITDB_ROOT_USERNAME=softdbd_user
          - MONGO_INITDB_ROOT_PASSWORD=softdbd_pass
        ports:
          - 31291:3030
        volumes:
            - ./resources:/resources
        networks: 
          - app-network          

    dbd_exam_vue_frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - 31290:8080
        networks: 
          - app-network              

networks:
  app-network:
    driver: "bridge"

