version: '3'

services:
    back_data_population:
        build:
            context: ./data_population
            dockerfile: dockerfile
        environment:
          - PRODUCTION_VARIABLES=1
          - POSTGRES_HOST=pg_dbd_exam
          - POSTGRES_USER=softdbd_user
          - POSTGRES_PASSWORD=softdbd_pass
          - POSTGRES_DB=softdbd_db
          - POSTGRES_PORT=31295
          - MONGO_INITDB_ROOT_USERNAME=softdbd_user
          - MONGO_INITDB_ROOT_PASSWORD=softdbd_pass
          - MONGO_PORT=30293
          - MONGO_HOST=mongo_basic_info_storage
          - MONGO_INITDB_DATABASE=softdbd_db
          - MEILI_HOST=search_engine
          - MEILI_PORT=31294
          - MEILI_MASTER_KEY=jaedenar_nutcracker
        ports:
          - 31292:31292
        volumes:
            - ./resources:/resources
        networks: 
          - app-network  
            
networks:
  app-network:
    driver: "bridge"
