# Mass initiation of databases
version: '3'


services:
    mongo_basic_info_storage:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: softdbd_user
            MONGO_INITDB_ROOT_PASSWORD: softdbd_pass
        ports:
            - 31293:27017
        volumes:
            - ./data/mongo/mongo_data:/data/db
            - ./data/mongo/mongo_config:/data/configdb

    search_engine:
        image: getmeili/meilisearch
        ports:
            - 31294:7700
        volumes:
            - ./data/meili/data.ms:/data.ms
#        environment:
#            - MEILI_MASTER_KEY=xxx

    pg_dbd_exam:
        image: postgres:11-alpine
        restart: always
        environment: 
          - POSTGRES_USER=softdbd_user
          - POSTGRES_PASSWORD=softdbd_pass
          - POSTGRES_DB=softdbd_db
          - POSTGRES_CONTAINER_NAME=pg_dbd
          - POSTGRES_PORT=31295
          - PGDATA=/var/lib/postgres/data
        ports: 
            - 31295:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks: 
          - app-network      

    redis_dbd_exam:
      container_name: redis
      hostname: redis
      image: redis
      ports:
          - "31296:6379"
      volumes:
          - ./data/redis:/data
      networks: 
          - app-network
          
    redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
          - REDIS_HOSTS=local:redis_dbd_exam:6379
      ports:
          - "31297:8081"
      networks: 
          - app-network
          
    meili-dashboard:
      image: shokme/meilisearch-dashboard
      ports:
        - 31298:80
      networks: 
        - app-network  

networks:
  app-network:
    driver: "bridge"
