version: '3'

services:
    back_data_population:
        build:
            context: ./data_population
            dockerfile: dockerfile
        environment:
          -  PRODUCTION_VARIABLES=1
        ports:
            - 31292:31292
        volumes:
          -  ./resources:/resources


    mongo_basic_info_storage:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: genusr
            MONGO_INITDB_ROOT_PASSWORD: genpassphrase
        ports:
            - 31293:27017
        volumes:
            - ./data/mongo/mongo_data:/data/db
            - ./data/mongo/mongo_config:/data/configdb


    search_engine:
        image: getmeili/meilisearch
        ports:
            - 31294:7700
        volumes:
            - ./data/meili/data.ms:/data.ms
#        environment:
#            - MEILI_MASTER_KEY=xxx

    pg_dbd_exam:
        image: postgres:11-alpine
        restart: always
        environment: 
          - POSTGRES_USER=softdbd
          - POSTGRES_PASSWORD=softdbd
          - POSTGRES_DB=pg_garbage
          - POSTGRES_CONTAINER_NAME=postgres2
          - POSTGRES_PORT=31295
          - PGDATA=/var/lib/postgres/data
        ports: 
            - 31295:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks: 
          - app-network      

    redis_dbd_exam:
      container_name: redis
      hostname: redis
      image: redis
      ports:
          - "31296:6379"
      volumes:
          - ./data/redis:/data
      networks: 
          - app-network
          
networks:
  app-network:
    driver: "bridge"

# volumes:
#     mongo_data:
#     mongo_config: