# Mass initiation of databases
version: '3'


services:
    mongo_basic_info_storage:
        container_name: mongo_basic_info_storage
        image: mongo:latest
        #environment:
            #- MONGO_INITDB_ROOT_USERNAME=softdbd_user
            #- MONGO_INITDB_ROOT_PASSWORD=softdbd_pass
        ports:
            - 31293:27017
        volumes:
            - ./data/mongo/mongo_data:/data/db
            - ./data/mongo/mongo_config:/data/configdb
        networks: 
          - app-network

    search_engine:
        container_name: search_engine
        image: getmeili/meilisearch
        ports:
            - 31294:7700
        volumes:
            - ./data/meili/data.ms:/data.ms
        networks: 
          - app-network
        environment:
            - MEILI_MASTER_KEY=jaedenar_nutcracker

    pg_dbd_exam:
        container_name: pg_dbd_exam
        image: postgres:11-alpine
        restart: always
        env_file: 
          - container_variables.env
        environment: 
          - POSTGRES_CONTAINER_NAME=pg_dbd
          # Overloaded over environment file.
          - POSTGRES_PORT=31295
          - PGDATA=/var/lib/postgres/data
        ports: 
            - 31295:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks: 
          - app-network      

    redis_dbd_exam:
      container_name: redis
      hostname: redis
      image: redis
      ports:
          - "31296:6379"
      volumes:
          - ./data/redis:/data
      networks: 
          - app-network
          
    redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
          - REDIS_HOSTS=local:redis_dbd_exam:6379
      ports:
          - "31297:8081"
      networks: 
          - app-network
          
    back_data_population:
        container_name: data-population
        build:
            context: ./data_population
            dockerfile: dockerfile
        env_file:
          - container_variables.env
        depends_on: 
            - pg_dbd_exam
            - redis-commander
            - redis_dbd_exam
            - search_engine
            - mongo_basic_info_storage
        volumes:
            - ./resources:/usr/src/resources

        networks: 
          - app-network

    dbd_exam_rust_backend:
        container_name: dbd_exam_rust_backend
        build:
            context: ./backend
            dockerfile: dockerfile
        env_file: 
          - container_variables.env
        ports:
          - 31291:3030
        volumes:
            - ./resources:/resources
        networks: 
          - app-network          

    dbd_exam_vue_frontend:
        container_name: dbd_exam_vue_frontend
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - 31290:8080
        networks: 
          - app-network

networks:
  app-network:
    driver: "bridge"
