# Newest non-nightly image doesn't support generic constants
# Meili can't compile on it.
FROM rustlang/rust:nightly

# Postgres
RUN apt-get install libpq-dev -y
RUN apt-get update

WORKDIR /usr/src/backend
COPY . .

RUN cargo install --path .
EXPOSE 11291
CMD ["backend"]